const sampleStocks = [
  {
    symbol: "RELIANCE",
    name: "Reliance Industries Ltd",
    sector: "Energy",
    price: 2540.75,
    change: +18.35,
    changePercent: "+0.73%",
    image: "https://companiesmarketcap.com/img/company-logos/512/RELIANCE.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "TCS",
    name: "Tata Consultancy Services Ltd",
    sector: "IT Services",
    price: 3805.10,
    change: -12.25,
    changePercent: "-0.32%",
    image: "https://companiesmarketcap.com/img/company-logos/512/TCS.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "INFY",
    name: "Infosys Ltd",
    sector: "IT Services",
    price: 1610.60,
    change: +6.45,
    changePercent: "+0.40%",
    image: "https://companiesmarketcap.com/img/company-logos/512/INFY.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank Ltd",
    sector: "Banking",
    price: 1575.30,
    change: +8.90,
    changePercent: "+0.57%",
    image: "https://companiesmarketcap.com/img/company-logos/512/HDFCBANK.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank Ltd",
    sector: "Banking",
    price: 1032.40,
    change: -5.20,
    changePercent: "-0.50%",
    image: "https://companiesmarketcap.com/img/company-logos/512/ICICIBANK.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "SBIN",
    name: "State Bank of India",
    sector: "Banking",
    price: 698.25,
    change: +4.35,
    changePercent: "+0.63%",
    image: "https://companiesmarketcap.com/img/company-logos/512/SBIN.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever Ltd",
    sector: "FMCG",
    price: 2504.95,
    change: -10.75,
    changePercent: "-0.43%",
    image: "https://companiesmarketcap.com/img/company-logos/512/HINDUNILVR.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "ITC",
    name: "ITC Ltd",
    sector: "FMCG",
    price: 457.80,
    change: +2.15,
    changePercent: "+0.47%",
    image: "https://companiesmarketcap.com/img/company-logos/512/ITC.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "BAJFINANCE",
    name: "Bajaj Finance Ltd",
    sector: "NBFC",
    price: 7542.15,
    change: -25.65,
    changePercent: "-0.34%",
    image: "https://companiesmarketcap.com/img/company-logos/512/BAJFINANCE.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "ASIANPAINT",
    name: "Asian Paints Ltd",
    sector: "Consumer Goods",
    price: 3240.55,
    change: +15.90,
    changePercent: "+0.49%",
    image: "https://companiesmarketcap.com/img/company-logos/512/ASIANPAINT.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "LT",
    name: "Larsen & Toubro Limited",
    sector: "Engineering & Construction",
    price: 3789.50,
    change: +25.20,
    changePercent: "+0.67%",
    image: "https://companiesmarketcap.com/img/company-logos/512/LT.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "MARUTI",
    name: "Maruti Suzuki India Ltd",
    sector: "Automobile",
    price: 9400.25,
    change: -55.40,
    changePercent: "-0.59%",
    image: "https://companiesmarketcap.com/img/company-logos/512/MARUTI.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "SUNPHARMA",
    name: "Sun Pharmaceutical Industries Ltd",
    sector: "Pharmaceuticals",
    price: 1608.30,
    change: +18.75,
    changePercent: "+1.18%",
    image: "https://companiesmarketcap.com/img/company-logos/512/SUNPHARMA.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "ADANIPORTS",
    name: "Adani Ports & SEZ Ltd",
    sector: "Logistics / Ports",
    price: 688.50,
    change: +7.80,
    changePercent: "+1.15%",
    image: "https://companiesmarketcap.com/img/company-logos/512/ADANIPORTS.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "WIPRO",
    name: "Wipro Ltd",
    sector: "IT Services",
    price: 507.75,
    change: -3.60,
    changePercent: "-0.70%",
    image: "https://companiesmarketcap.com/img/company-logos/512/WIPRO.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "HCLTECH",
    name: "HCL Technologies Ltd",
    sector: "IT Services",
    price: 1253.20,
    change: +10.15,
    changePercent: "+0.82%",
    image: "https://companiesmarketcap.com/img/company-logos/512/HCLTECH.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "LTIM",
    name: "Larsen & Toubro Infotech Ltd",
    sector: "IT Services",
    price: 6495.40,
    change: +30.60,
    changePercent: "+0.47%",
    image: "https://companiesmarketcap.com/img/company-logos/512/LTIM.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "ONGC",
    name: "Oil & Natural Gas Corporation Ltd",
    sector: "Oil & Gas",
    price: 323.70,
    change: -2.85,
    changePercent: "-0.87%",
    image: "https://companiesmarketcap.com/img/company-logos/512/ONGC.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "BPCL",
    name: "Bharat Petroleum Corporation Ltd",
    sector: "Energy / Oil & Gas",
    price: 420.00,
    change: +4.50,
    changePercent: "+1.08%",
    image: "https://companiesmarketcap.com/img/company-logos/512/BPCL.NS.png",
    exchange: "NSE",
  },
  {
    symbol: "TATAMOTORS",
    name: "Tata Motors Ltd",
    sector: "Automobile",
    price: 875.25,
    change: -8.50,
    changePercent: "-0.96%",
    image: "https://companiesmarketcap.com/img/company-logos/512/TATAMOTORS.NS.png",
    exchange: "NSE",
  }, 
];

module.exports = { data: sampleStocks };
